FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

WORKDIR /app

RUN apt update && apt install -y \
    libgl1-mesa-glx \
    libx11-6 \
    qtbase5-dev \
    libxcb-cursor0 \
    && apt clean

# ---------------------------------------------
# 📦 Instalar librerías de RealSense
# ---------------------------------------------
RUN mkdir -p /etc/apt/keyrings && \
    curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp \
    | tee /etc/apt/keyrings/librealsense.pgp > /dev/null && \
    echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] \
    https://librealsense.intel.com/Debian/apt-repo \
    $(lsb_release -cs) main" \
    | tee /etc/apt/sources.list.d/librealsense.list && \
    apt-get update && apt-get install -y \
    librealsense2-utils librealsense2-dev \
    && rm -rf /var/lib/apt/lists/*


COPY . /app

RUN pip install --no-cache-dir \
    "numpy<2" \
    opencv-python \
    ultralytics \
    pyrealsense2 \
    PySide6

CMD ["python", "launcher.py"]
