FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

WORKDIR /app

RUN apt update && apt install -y \
    libgl1-mesa-glx \
    libx11-6 \
    qtbase5-dev \
    libxcb-cursor0 \
    && apt clean

COPY . /app

RUN pip install --no-cache-dir \
    "numpy<2" \
    opencv-python \
    ultralytics \
    PySide6

CMD ["python", "launcher.py"]
